# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreA', models.CharField(max_length=100)),
                ('puntajeDannoA', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreH', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoArmamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTA', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='armamento',
            name='habilidadA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armamento.Habilidad'),
        ),
        migrations.AddField(
            model_name='armamento',
            name='tipoA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armamento.TipoArmamento'),
        ),
    ]
