# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreT', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='armamento',
            name='tipoA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armamento.Tipo'),
        ),
        migrations.DeleteModel(
            name='TipoArmamento',
        ),
    ]
