# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armamento', '0002_auto_20200526_0258'),
        ('soldado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='soldadoarmamento',
            name='SoldadoSA',
        ),
        migrations.RemoveField(
            model_name='soldadoarmamento',
            name='armamentoSA',
        ),
        migrations.RemoveField(
            model_name='baseconocimiento',
            name='SoldadoBC',
        ),
        migrations.RemoveField(
            model_name='baseconocimiento',
            name='armamentoBC',
        ),
        migrations.RemoveField(
            model_name='soldado',
            name='actividadS',
        ),
        migrations.RemoveField(
            model_name='soldado',
            name='estadoS',
        ),
        migrations.RemoveField(
            model_name='soldado',
            name='nombreS',
        ),
        migrations.AddField(
            model_name='baseconocimiento',
            name='Soldado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldado.Soldado'),
        ),
        migrations.AddField(
            model_name='baseconocimiento',
            name='armamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armamento.Armamento'),
        ),
        migrations.AddField(
            model_name='soldado',
            name='armamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armamento.Armamento'),
        ),
        migrations.AddField(
            model_name='soldado',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SoldadoArmamento',
        ),
        migrations.DeleteModel(
            name='TipoSoldado',
        ),
        migrations.AddField(
            model_name='soldado',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldado.Tipo'),
        ),
    ]
